name = "page-scroll-master-feedback"
main = "worker.js"
compatibility_date = "2026-06-14"
workers_dev = true

[observability]
enabled = false

[triggers]
crons = ["37 3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "page-scroll-master-feedback-db"
database_id = "62c387f4-8de2-49c9-b10c-0be09869542e"
