name = "page-scroll-master-analytics"
main = "worker.js"
compatibility_date = "2026-06-13"
workers_dev = true

[observability]
enabled = false

[triggers]
crons = ["17 3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "page-scroll-master-analytics-db"
database_id = "8b1fad3c-ff50-4291-850d-5252f799e28a"

